import { createClient } from '@/lib/supabase/server'
import { requireActivePlan } from '@/lib/plan'
import { notFound } from 'next/navigation'
import PrintButton from './PrintButton'

export default async function InvoicePage({ params }: { params: { id: string } }) {
  await requireActivePlan()
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const { data: company } = await supabase.from('companies').select('id, name, country').eq('owner_id', user!.id).single()

  const { data: summary } = await supabase
    .from('payroll_summaries')
    .select('*, contractors(name, role, email, country)')
    .eq('id', params.id)
    .eq('company_id', company?.id ?? '')
    .maybeSingle()
  if (!summary) notFound()

  const contractor = summary.contractors as { name: string; role: string; email: string; country: string } | null
  const invoiceNo = `SA-${summary.period_start.replace(/-/g, '').slice(0, 6)}-${String(summary.id).slice(0, 6).toUpperCase()}`

  return (
    <div className="min-h-screen bg-slate-100 print:bg-white py-10 print:py-0">
      <div className="max-w-2xl mx-auto mb-4 flex justify-end print:hidden px-4">
        <PrintButton />
      </div>

      <div className="max-w-2xl mx-auto bg-white rounded-xl print:rounded-none shadow-sm print:shadow-none border border-slate-200 print:border-0 p-10">
        <div className="flex items-start justify-between mb-10">
          <div>
            <div className="text-xl font-black text-navy-deep">
              Staffing<span className="text-amber">Atlas</span>
            </div>
            <p className="text-xs text-slate-400 mt-1">Contractor Payment Summary</p>
          </div>
          <div className="text-right">
            <p className="text-sm font-bold text-slate-900">{invoiceNo}</p>
            <p className="text-xs text-slate-400">Issued {new Date().toLocaleDateString()}</p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-8 mb-10">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1.5">Bill to</p>
            <p className="font-semibold text-slate-900">{company?.name}</p>
            {company?.country && <p className="text-sm text-slate-500">{company.country}</p>}
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-1.5">Contractor</p>
            <p className="font-semibold text-slate-900">{contractor?.name}</p>
            <p className="text-sm text-slate-500">{contractor?.role}</p>
            <p className="text-sm text-slate-500">{contractor?.email}</p>
          </div>
        </div>

        <table className="w-full text-sm mb-10">
          <thead>
            <tr className="border-b-2 border-slate-900 text-[10px] uppercase tracking-wider text-slate-400">
              <th className="text-left py-2 font-bold">Description</th>
              <th className="text-right py-2 font-bold">Hours</th>
              <th className="text-right py-2 font-bold">Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-slate-100">
              <td className="py-4">
                <p className="font-medium text-slate-900">Contract work — {contractor?.role}</p>
                <p className="text-xs text-slate-400">
                  {new Date(summary.period_start).toLocaleDateString()} – {new Date(summary.period_end).toLocaleDateString()}
                </p>
              </td>
              <td className="py-4 text-right text-slate-600">{Number(summary.total_hours).toFixed(1)}</td>
              <td className="py-4 text-right font-medium text-slate-900">
                {summary.currency} {Number(summary.total_amount).toFixed(2)}
              </td>
            </tr>
          </tbody>
          <tfoot>
            <tr>
              <td colSpan={2} className="py-4 text-right font-bold text-slate-900">Total due</td>
              <td className="py-4 text-right text-lg font-black text-slate-900">
                {summary.currency} {Number(summary.total_amount).toFixed(2)}
              </td>
            </tr>
          </tfoot>
        </table>

        <div className="border-t border-slate-100 pt-6 flex items-center justify-between">
          <p className="text-xs text-slate-400">
            Status: <span className="font-semibold capitalize">{summary.status}</span> · Generated by StaffingAtlas — this is a payment summary, not a tax invoice.
          </p>
        </div>
      </div>
    </div>
  )
}
